import {useEffect,useMemo,useState} from 'react';
import {ArrowUpRight,CheckCircle2,ChevronDown,CircleHelp,Clock3,GitBranch,Layers3,Link2,Search,SlidersHorizontal,TriangleAlert,X} from 'lucide-react';
import {ms,type Mission} from './api';
import './corpus-board.css';

type CellStatus='supported'|'partly_supported'|'contradicted'|'not_applicable'|'unknown';
type Citation={span_id:string;source_id:string;url:string;quote:string;start:number;end:number};
type Cell={criterion_id:string;status:CellStatus;finding_ids:string[];decision_ids:string[];citations:Citation[];confidence:number|null};
type Column={id:string;label:string;question:string};
type CorpusRow={id:string;source_id:string;title:string;url:string;role:string;evidence_basis:string;cells:Cell[];assessment_ms:number|null;question_count:number;estimated_usd:number|null;decision_ids?:string[];jev_calls?:number;cached_calls?:number};
type Rollup={criterion_id:string;label:string;denominator:number;supported:number;partly_supported:number;contradicted:number;not_applicable:number;unknown:number};
type Feature={id:string;label:string;denominator:number;unknown:number;values:{value:string;label:string;count:number;source_ids:string[]}[]};
type Corpus={program_id:string;unit:string;scope:string;columns:Column[];rows:CorpusRow[];rollups:Rollup[];features:Feature[];metrics:{items:number;typed_judgments:number;jev_calls:number;cached_calls:number;median_item_ms:number|null;analysis_wall_ms:number|null;items_per_second:number|null;judgments_per_second:number|null;estimated_usd:number|null;cost_known_calls:number;cost_unknown_calls:number};limitations:string[]};
type Props={mission:Mission;onSource:(id:string)=>void;onDecision:(id:string)=>void};

const statusLabels:Record<CellStatus,string>={supported:'Supported',partly_supported:'Partial evidence',contradicted:'Contradicted',not_applicable:'Not applicable',unknown:'Unknown'};
const roleLabels:Record<string,string>={primary_artifact:'Original record',original_measurement:'Original measurement',secondary_commentary:'Commentary',company_page:'Company page',unknown:'Role unverified'};
const count=(value:number)=>value.toLocaleString();
const finite=(value:number|null|undefined):value is number=>typeof value==='number'&&Number.isFinite(value);
const money=(value:number|null)=>finite(value)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:4}).format(value):'—';
const needsReview=(row:CorpusRow)=>row.cells.some(cell=>['partly_supported','unknown','contradicted'].includes(cell.status));
const evidenceCount=(row:CorpusRow)=>row.cells.filter(cell=>cell.status==='supported').length;
function host(url:string){try{return new URL(url).hostname.replace(/^www\./,'');}catch{return url;}}
function segments(rollup:Rollup){return (['supported','partly_supported','contradicted','not_applicable','unknown'] as const).map(status=>({status,value:rollup[status]||0}));}

/** A projection of saved source assessments. Every bar and timing comes from the run. */
export default function CorpusBoard({mission,onSource,onDecision}:Props){
 const [query,setQuery]=useState(''),[reviewOnly,setReviewOnly]=useState(false),[sort,setSort]=useState('collected'),[visible,setVisible]=useState(12),[featureFilter,setFeatureFilter]=useState<{label:string;sourceIds:string[]}|null>(null);
 useEffect(()=>{setQuery('');setReviewOnly(false);setSort('collected');setVisible(12);setFeatureFilter(null);},[mission.id]);
 const corpus=mission.corpus as Corpus|undefined;
 const all=corpus?.rows||[];
 const filtered=useMemo(()=>{
  const needle=query.trim().toLocaleLowerCase();
  const result=all.filter(row=>(!reviewOnly||needsReview(row))&&(!featureFilter||featureFilter.sourceIds.includes(row.source_id)||featureFilter.sourceIds.includes(row.id))&&(!needle||[row.title,row.url,row.role,...row.cells.flatMap(cell=>cell.citations.map(citation=>citation.quote))].join(' ').toLocaleLowerCase().includes(needle)));
  if(sort==='supported')result.sort((a,b)=>evidenceCount(b)-evidenceCount(a)||a.title.localeCompare(b.title));
  if(sort==='name')result.sort((a,b)=>a.title.localeCompare(b.title));
  return result;
 },[all,query,reviewOnly,sort,featureFilter]);
 if(!corpus||(!corpus.columns.length&&!all.length))return null;
 const active=['running','pausing'].includes(mission.status),metrics=corpus.metrics;
 if(!all.length)return <section className="corpus-board corpus-pending" aria-label="Jev collection analysis"><Layers3 size={20}/><div><strong>{active?'Building the evidence comparison':'No current records to compare'}</strong><p>{active?`Jev will check collected records against ${corpus.columns.length} shared research questions. Rows appear as their assessments arrive.`:'This run has not established comparable records. The collected source findings remain available in Results.'}</p></div></section>;
 const reviewCount=all.filter(needsReview).length;
 const hasFilter=!!query||reviewOnly||!!featureFilter;
 const reset=()=>{setQuery('');setReviewOnly(false);setFeatureFilter(null);setVisible(12);};
 const cells=(row:CorpusRow)=>corpus.columns.map(column=>{
  const cell=row.cells.find(value=>value.criterion_id===column.id);
  const status=cell?.status||'unknown';
  const citation=cell?.citations[0];
  const StatusIcon=status==='supported'?CheckCircle2:status==='contradicted'?TriangleAlert:CircleHelp;
  return <td key={column.id} data-label={column.label}><button className={'corpus-cell corpus-'+status} onClick={()=>onSource(citation?.source_id||row.source_id)} aria-label={`${column.label}: ${statusLabels[status]}. Inspect source for ${row.title}`} title={citation?.quote||`Inspect the collected source. ${statusLabels[status]} for this research question.`}><span className="corpus-cell-status"><StatusIcon size={13}/>{statusLabels[status]}</span>{citation?<span className="corpus-cell-quote">{citation.quote}</span>:<span className="corpus-cell-empty">{status==='not_applicable'?'Outside this question’s scope':'No checked passage answers this question'}</span>}<span className="corpus-cell-link"><Link2 size={11}/>{citation?'Read evidence':'Inspect source'}{(cell?.citations.length||0)>1&&<span>+{cell!.citations.length-1}</span>}</span></button></td>;
 });
 return <section className="corpus-board" aria-label="Jev collection analysis">
  <div className="corpus-heading"><div><span className="corpus-eyebrow"><Layers3 size={13}/> JEV · COLLECTION ANALYSIS</span><h2>The evidence, side by side.</h2><p>Each collected record, checked against the same research questions. Open a cell to inspect its source.</p></div><span className={'corpus-run-state '+(active?'is-live':'')}><i/>{mission.mode==='fixture'?'Test fixture':active?'Updating with this run':'Saved analysis'}</span></div>
  <div className="corpus-stats" aria-label="Measured collection statistics"><div><span>Records compared</span><strong>{count(metrics.items)}</strong><small>{corpus.columns.length} shared research questions</small></div><div><span>Typed Jev answers</span><strong>{count(metrics.typed_judgments)}</strong><small>{count(metrics.jev_calls)} live requests{metrics.cached_calls>0?` · ${count(metrics.cached_calls)} cached`:''}</small></div><div><span>Median item request time</span><strong>{ms(metrics.median_item_ms)}</strong><small>Measured request round trips per item</small></div><div><span>Estimated Jev cost</span><strong>{metrics.cost_known_calls?money(metrics.estimated_usd):'—'}</strong><small>{metrics.cost_unknown_calls?`${metrics.cost_unknown_calls} request costs unavailable`:'Collection assessments only'}</small></div></div>
  <div className="corpus-controls"><label className="corpus-search"><Search size={15}/><input aria-label="Search compared records" value={query} onChange={event=>{setQuery(event.target.value);setVisible(12)}} placeholder="Find a record or passage"/></label><label className="corpus-sort"><SlidersHorizontal size={14}/><select aria-label="Sort compared records" value={sort} onChange={event=>{setSort(event.target.value);setVisible(12)}}><option value="collected">Collection order</option><option value="supported">Most supported questions</option><option value="name">Name A–Z</option></select></label><label className="corpus-review"><input type="checkbox" checked={reviewOnly} onChange={event=>{setReviewOnly(event.target.checked);setVisible(12)}}/>Needs review <span>{reviewCount}</span></label></div>
  {featureFilter&&<div className="corpus-filter-chip"><span>Classification: {featureFilter.label}</span><button onClick={()=>setFeatureFilter(null)} aria-label="Clear classification filter"><X size={13}/></button></div>}
  <div className="corpus-table-caption"><span>{hasFilter?`${filtered.length} of ${all.length}`:all.length} {all.length===1?'record':'records'}{filtered.length>visible?` · showing ${visible}`:''}</span><span>Unknowns stay visible</span></div>
  {!!filtered.length&&<div className="corpus-table-scroll" tabIndex={0} role="region" aria-label="Evidence comparison table"><table className="corpus-table"><thead><tr><th scope="col">Collected record</th>{corpus.columns.map(column=><th scope="col" key={column.id}><span>{column.label}</span><small title={column.question}>{column.question.split(' Research goal: ')[0]}</small></th>)}<th scope="col">Jev analysis<small>Saved request measurements</small></th></tr></thead><tbody>{filtered.slice(0,visible).map((row,index)=>{
   const decisions=[...new Set(row.decision_ids||row.cells.flatMap(cell=>cell.decision_ids))];
   return <tr key={row.id}><th scope="row"><span className="corpus-row-index">{String(index+1).padStart(2,'0')}</span><button className="corpus-record-title" onClick={()=>onSource(row.source_id)}>{row.title||host(row.url)}<ArrowUpRight size={12}/></button><span className="corpus-record-host">{host(row.url)}</span><span className="corpus-record-role">{roleLabels[row.role]||row.role.replaceAll('_',' ')}</span>{row.evidence_basis&&<span className="corpus-record-basis">{row.evidence_basis}</span>}</th>{cells(row)}<td className="corpus-analysis" data-label="Jev analysis"><span className="corpus-row-time"><Clock3 size={13}/>{ms(row.assessment_ms)}</span><span>{count(row.question_count)} typed answers</span>{row.jev_calls!=null&&<small>{row.jev_calls} live requests{row.cached_calls?` · ${row.cached_calls} cached`:''}</small>}{decisions.length>0&&<button className="corpus-decision-link" onClick={()=>onDecision(decisions[0])}><GitBranch size={12}/> Inspect Jev{decisions.length>1?` · ${decisions.length} requests`:''}</button>}{decisions.length>1&&<details className="corpus-request-list"><summary>All linked requests</summary>{decisions.map((id,decisionIndex)=><button key={id} onClick={()=>onDecision(id)}>Request {decisionIndex+1}<ArrowUpRight size={10}/></button>)}</details>}</td></tr>;
  })}</tbody></table></div>}
  {!filtered.length&&<div className="corpus-empty"><Layers3 size={24}/><h3>{all.length?'No records match these filters':active?'Building the comparison':'No current records to compare'}</h3><p>{all.length?'Clear a filter to return to the collected evidence.':active?'The first row appears when Jev has assessed an original record against the research questions.':"This run has not established comparable records. The source findings below retain what was collected."}</p>{hasFilter&&<button onClick={reset}>Clear filters <X size={12}/></button>}</div>}
  {filtered.length>visible&&<button className="corpus-show-more" onClick={()=>setVisible(value=>value+12)}>Show {Math.min(12,filtered.length-visible)} more records <ChevronDown size={14}/></button>}
  {!!all.length&&<details className="corpus-distributions"><summary><span>Coverage across this collection <small>{all.length} records · every unknown included</small></span><ChevronDown size={16}/></summary><div className="corpus-coverage-grid">{corpus.rollups.map(rollup=><article className="corpus-coverage" key={rollup.criterion_id}><div><h3>{rollup.label}</h3><span>{rollup.supported}/{rollup.denominator} supported</span></div><div className="corpus-bar" role="img" aria-label={`${rollup.label}: ${segments(rollup).map(segment=>`${segment.value} ${statusLabels[segment.status].toLowerCase()}`).join(', ')}. ${rollup.denominator} records total.`}>{segments(rollup).filter(segment=>segment.value>0).map(segment=><span className={'corpus-bar-'+segment.status} style={{width:`${rollup.denominator?segment.value/rollup.denominator*100:0}%`}} key={segment.status} title={`${segment.value} ${statusLabels[segment.status]}`}/>)}</div><div className="corpus-bar-legend">{segments(rollup).map(segment=><span key={segment.status}><i className={'corpus-bar-'+segment.status}/>{segment.value} {statusLabels[segment.status].toLowerCase()}</span>)}</div></article>)}</div><p className="corpus-distribution-note">Coverage describes the records collected in this run. It is not a market share, popularity or accuracy score. Filtering the table does not change these collection totals.</p></details>}
  {!!corpus.features.length&&<details className="corpus-distributions corpus-classifications"><summary><span>Observed classifications <small>From Jev’s saved evidence checks</small></span><ChevronDown size={16}/></summary><div className="corpus-coverage-grid">{corpus.features.map(feature=><article className="corpus-feature" key={feature.id}><h3>{feature.label}</h3><p>{feature.denominator} records · {feature.unknown} unknown</p>{feature.values.map(value=><button className="corpus-feature-value" key={value.value} onClick={()=>{setFeatureFilter({label:`${feature.label}: ${value.label}`,sourceIds:value.source_ids});setVisible(12)}}><span>{value.label}<b>{value.count}/{feature.denominator}</b></span><span className="corpus-feature-track"><i style={{width:`${feature.denominator?value.count/feature.denominator*100:0}%`}}/></span><small>Show matching records <ArrowUpRight size={10}/></small></button>)}</article>)}</div></details>}
  <div className="corpus-footnote"><Clock3 size={13}/><p>Item timing adds the measured network and provider round trips for its linked Jev requests. Cached requests are excluded. This is not end-to-end research time or a comparison with another model. {metrics.cost_unknown_calls>0?'The cost total is unavailable because some request estimates are missing. ':''}LLM, search and acquisition costs are excluded.</p></div>
  {!!corpus.limitations.length&&<details className="corpus-method"><summary>Scope &amp; measurement notes</summary>{corpus.scope&&<p>{corpus.scope}</p>}<ul>{corpus.limitations.map((limitation,index)=><li key={index}>{limitation}</li>)}</ul>{finite(metrics.analysis_wall_ms)&&<p>Measured analysis window: {ms(metrics.analysis_wall_ms)}.{finite(metrics.items_per_second)&&` ${metrics.items_per_second.toFixed(2)} records per second over that window.`} This spans the first linked request through the last completion, including gaps, and is specific to this run.</p>}</details>}
 </section>;
}
