import {isValidElement,useEffect,useId,useMemo,useRef,useState,type ReactNode} from 'react';
import {ArrowLeft,ArrowRight,ArrowUpRight,BookOpen,Check,ChevronRight,Compass,FileText,GitBranch,Globe,KeyRound,LifeBuoy,Monitor,Search,ShieldCheck,SlidersHorizontal,Sparkles,Wallet,X,type LucideIcon} from 'lucide-react';
import './guide.css';

export type GuideProps={
 onSettings:(kind:'jev'|'search')=>void;
 onClose?:()=>void;
 onStart?:()=>void;
 initialSection?:string;
};
type Section={id:string;title:string;description:string;icon:LucideIcon;content:ReactNode};
function textContent(node:ReactNode):string{
 if(typeof node==='string'||typeof node==='number')return String(node);
 if(Array.isArray(node))return node.map(textContent).join(' ');
 if(isValidElement<{children?:ReactNode}>(node))return textContent(node.props.children);
 return '';
}
function Note({children}:{children:ReactNode}){return <div className="guide-note"><BookOpen size={17}/><div>{children}</div></div>}

export default function Guide({onSettings,onClose,onStart,initialSection='start'}:GuideProps){
 const [selected,setSelected]=useState(initialSection),[query,setQuery]=useState('');
 const searchId=useId(),article=useRef<HTMLElement>(null);
 useEffect(()=>{setSelected(initialSection);setQuery('')},[initialSection]);
 const sections=useMemo<Section[]>(()=>[
  {id:'start',title:'Getting started',description:'Your question is the starting point.',icon:Compass,content:<>
   <p className="guide-lead">Tell Jev what you want to understand. It turns your goal into research questions, gathers evidence and compares what it finds.</p>
   <div className="guide-prompt"><span>TRY A QUESTION LIKE THIS</span><p>Find viral videos about home cooking. Compare individual videos, their title approaches, formats and observed engagement. Investigate what might explain their reach.</p><small>You can also ask for competitors, product improvements, technical comparisons or research into a specific claim. Starting websites are optional.</small></div>
   <ol className="guide-steps">
    <li><div><h3>Ask your question</h3><p>Live is the start page, with “What are you looking for?” and a few examples. Name your topic and what you want to learn. Press Start research or Enter.</p></div></li>
    <li><div><h3>Watch Jev shape the investigation</h3><p>The live view opens immediately. Jev chooses what to investigate and which evidence matters for your goal. Expand Jev’s research approach to see the selected questions and its actual planning decision.</p></div></li>
    <li><div><h3>Follow the evidence</h3><p>Jev selects individual sources, checks their relevance and asks more focused questions when evidence is missing. The scene shows these actual decisions and measured response times as work happens.</p></div></li>
    <li><div><h3>Explore the comparison</h3><p>Open Results for individual objects, evidence-linked findings and comparisons. Observed patterns, possible explanations and unsupported ideas are labeled separately. Use the proposed next test to decide what to investigate next.</p></div></li>
   </ol>
   <p>Opening or refreshing Radar always returns to Live. Choose <strong>Saved</strong> to reopen an investigation; a running investigation continues on the server.</p>
   <Note>First run? The server needs a <strong>TypeSafe key for Jev</strong> and a <strong>Brave Search key for automatic web discovery</strong>. Configure these once, then start with a question. An optional text model can propose tailored research questions and draft an evidence-linked answer for Jev to check.</Note>
   <div className="guide-actions">{onStart&&<button className="primary" onClick={onStart}>Start an investigation <ArrowRight size={15}/></button>}<button className="secondary" onClick={()=>onSettings('search')}><KeyRound size={15}/> Check connections</button></div>
  </>},
  {id:'keys',title:'API keys & setup',description:'One-time configuration on the server.',icon:KeyRound,content:<>
   <p className="guide-lead">Brave discovers public sources and individual video records. Jev designs the research approach, makes choices, assesses evidence and compares the collected objects.</p>
   <div className="guide-provider-grid"><div><Globe size={21}/><h3>Brave Search</h3><p>Finds public webpages and indexed video records from the research queries. Required for automatic general-web discovery.</p><a href="https://api-dashboard.search.brave.com/" target="_blank" rel="noreferrer">Brave API dashboard <ArrowUpRight size={13}/></a></div><div><GitBranch size={21}/><h3>TypeSafe · Jev</h3><p>Runs the structured decisions that guide and evaluate research.</p><a href="https://docs.typesafe.ai/introduction" target="_blank" rel="noreferrer">TypeSafe setup documentation <ArrowUpRight size={13}/></a></div></div>
   <h3>1. Save the keys in the project’s .env</h3><p>The installer creates a private <code>.env</code> if one does not already exist. On the machine running Radar, edit that file in the project root—the directory containing <code>backend</code>, <code>frontend</code> and <code>scripts</code>. Replace these placeholders with your own keys:</p>
   <pre aria-label="Server environment variable example"><code>{'TYPESAFE_API_KEY=your_typesafe_key\nBRAVE_SEARCH_API_KEY=your_brave_search_key'}</code></pre>
   <p>Keep both keys on the server. Do not put them in a frontend environment file, research prompt or shared report. The application displays connection status, never the saved key values.</p>
   <h3>2. Reload the connection</h3><p>Open Workspace settings and choose <strong>Reload keys</strong>. It reads both saved keys without making a provider request. If the key is still missing, check the exact variable name and that you edited this project’s file.</p>
   <h3>3. Check Jev, then research</h3><p>In Workspace settings, <strong>Test Jev connection</strong> checks TypeSafe with a small provider request. That test can incur a charge. Once the connections are ready, return to your question and press Start research.</p>
   <h3>4. Optional: add a text model</h3><p>Settings → API connections includes a provider selector for <strong>OpenAI, Google Gemini, Anthropic, OpenRouter or an OpenAI-compatible endpoint</strong>. Choose your provider and model, add its key to the server <code>.env</code>, reload keys and save the selection. Each provider remembers its saved model.</p><pre><code>{'OPENAI_API_KEY=your_openai_key\n# Or: GEMINI_API_KEY / ANTHROPIC_API_KEY / OPENROUTER_API_KEY\n# Custom endpoint: TEXT_MODEL_API_KEY + TEXT_MODEL_BASE_URL'}</code></pre><p>You only need the key for the provider you select. Keys are never entered in the browser. For Google Gemini, create a key in <a href="https://aistudio.google.com/apikey" target="_blank" rel="noreferrer">Google AI Studio</a> and use <code>GEMINI_API_KEY</code> (<code>GOOGLE_API_KEY</code> is also accepted). Select Google Gemini, enter a bare model ID and save. The output-token limit includes thinking tokens. Check the model’s price estimates under <strong>Model prices, limits &amp; data sharing</strong>; if the price is unknown, enter both input and output estimates before testing. <strong>Test text model</strong> sends one small paid request only when clicked; saving or reloading does not. You can leave the provider Off to continue with Jev’s bounded research workflow.</p>
   <h3>5. Set your spend limits</h3><p>Open <strong>Settings → Spend limits</strong>. The defaults are <strong>$5 for Jev and $20 for the LLM per investigation</strong>. These are estimated ceilings, not expected charges. Page, time, request and token limits can stop a run sooner. Search-provider charges are separate.</p>
   <div className="guide-actions"><button className="primary" onClick={()=>onSettings('search')}>Open connection settings <ArrowRight size={15}/></button><button className="secondary" onClick={()=>onSettings('jev')}>Open Jev settings</button></div>
   <Note>If someone else hosts this workspace, ask the operator to configure the server. Each self-hosted installation uses its own provider accounts.</Note>
  </>},
  {id:'jev',title:'What Jev does',description:'See how decisions shape the investigation.',icon:GitBranch,content:<>
   <p className="guide-lead">Your goal changes what Jev investigates. Radar builds structured questions and bounded choices around that goal; Jev selects an approach and makes the decisions that move the investigation forward.</p>
   <div className="guide-decision-flow" aria-label="Jev's role in research"><span><GitBranch size={17}/>Plan</span><ChevronRight size={15}/><span><Search size={17}/>Investigate</span><ChevronRight size={15}/><span><Compass size={17}/>Refine</span><ChevronRight size={15}/><span><Check size={17}/>Verify</span><ChevronRight size={15}/><span><Sparkles size={17}/>Compare</span></div>
   <dl className="guide-definitions">
    <div><dt>Design the approach</dt><dd>Jev selects the research unit, method and evidence priorities: individual videos, companies, articles, technical artifacts or claims. With a text model configured, it proposes questions and searches tailored to your goal; Jev approves the research questions before they guide the investigation. With it off, Radar configures bounded questions and queries from Jev’s typed choices and your goal.</dd></div>
    <div><dt>Investigate the objects themselves</dt><dd>Jev chooses which sources to inspect and distinguishes primary artifacts from commentary about them. For video research, a list of “viral videos” is a lead; individual video records are the objects to compare.</dd></div>
    <div><dt>Refine unanswered questions</dt><dd>When the current queue leaves gaps, Jev can select a more focused discovery query. Those choices use the actual goal, missing evidence and previous attempts, including sources screened out as irrelevant. Unhelpful sources guide the next search without becoming supporting evidence.</dd></div>
    <div><dt>Link and check evidence</dt><dd>Jev selects existing passages and assesses whether they support each research question. Missing answers stay unknown; a partial answer retains its qualification.</dd></div>
    <div><dt>Compare and choose a next test</dt><dd>Jev compares observations across the inspected artifacts. Recurring observations, tentative explanations and unsupported comparisons stay distinct. With a text model, missing evidence informs new follow-up proposals and Jev chooses which permitted search to execute within the remaining limits. The recorded activity distinguishes these executed searches from recommendations for your business, which are not performed automatically.</dd></div>
   </dl>
   <h3>Compare the collection</h3><p>The collection panel applies the same research questions across inspected original records. Its matrix shows supported answers, partial evidence, contradictions and unknowns. Open a cell for the source and exact saved decision; use Needs review to find gaps. Classification summaries retain their denominator and unknown count. These describe the collected sample, not the whole market.</p><p>Jev can accept or defer several independent leads in one request. Accepted records run in small concurrent groups within your limits. Timings and throughput come from recorded requests; they are not an assumed speedup or a promise of exhaustive coverage. Research matrix CSV exports the comparison.</p>
   <h3>Give each model a clear job</h3><p><strong>Text model proposes → Jev decides → Browser gathers → Jev checks → Evidence-linked answer.</strong> The optional text model supplies goal-specific proposals and drafts conclusions from saved findings. Jev selects the permitted next actions and checks draft claims against their cited passages. Unsupported claims are withheld; hypotheses and recommendations retain their qualifications.</p>
   <h3>Make the decision visible</h3><p>The Live view shows Jev at the center of the work. Open its selected choice to inspect the real request and answer, or open a source to read the collected text. Movement follows recorded work; the visualization pauses when work stops. Pause visuals freezes movement without stopping research. Reduced-motion preferences are respected.</p>
   <p>Request timing includes network travel and provider processing. A cached decision is marked as cached. Text model requests have a separate activity panel and measured round-trip; they are never counted as Jev calls. These measurements do not establish a speed advantage over another model or workflow.</p>
   <Note>Jev’s structured answers are assessments, not independent factual verification. A cited company claim can still be inaccurate, and bounded research cannot establish that every competitor has been found.</Note>
  </>},
  {id:'research',title:'Research & results',description:'Turn a comparison into a useful decision.',icon:SlidersHorizontal,content:<>
   <p className="guide-lead">Start with the question you need answered. Use the evidence to choose your next step.</p>
   <h3>Give the investigation a clear aim</h3><p>Name the product or topic, audience, market and information you care about. For example: “Compare collaboration tools for a small design team, focusing on guest access and public pricing.” The same workflow supports videos, articles, technical tools, product research and custom questions.</p>
   <h3>Read Jev’s research approach</h3><p>Expand the approach card in Live or Results to see what is being investigated and what evidence Jev needs. The optional pre-start preview contains provisional questions. If you edit the questions yourself, Radar preserves your custom criteria.</p>
   <h3>Read the research answer</h3><p>When a text model is configured and enough evidence is available, Results opens with a written answer. Each displayed claim has cited passages checked by Jev. Expand a citation to inspect the source and finding. Qualified conclusions and possible explanations remain labeled, recommendations are proposed actions, and unanswered questions are listed explicitly. Changing the scope or rejecting supporting evidence hides an outdated answer until it is reassessed.</p>
   <h3>Read the candidate list</h3><p>Use relevance to find useful matches, or sort by collected evidence, name and observed search visibility. Relationship and pricing filters help narrow the inspected results. The reference product is kept separate from candidate alternatives and background sources.</p>
   <div className="guide-term"><strong>Search visibility is an observation</strong><p>It describes appearances in this investigation’s saved provider responses. It does not measure overall popularity, traffic or market share. The supporting query, provider, position and observation time remain available.</p></div>
   <h3>Inspect before you act</h3><p>Click a comparison excerpt to read the exact source passage. Review the retrieval date, what the question asked, and any qualification. “Unknown” means the inspected evidence did not establish an answer; it does not mean a feature or price does not exist.</p>
   <h3>Understand comparison labels</h3><p><strong>Observed pattern</strong> describes the inspected sample. <strong>Possible explanation</strong> is a hypothesis to test. <strong>Insufficient evidence</strong> means the supplied observations cannot support the comparison. Open a citation to inspect the source behind any conclusion.</p>
   <h3>Explore the proposed improvements</h3><p>Compare the reference and candidate excerpts, then read the proposed test and its success measure. Validate an important claim with a suitable primary source or user study before treating it as a product requirement.</p>
   <h3>Refine when needed</h3><p>Research options let you change questions, geography, language, exclusions and limits. Optional starting websites can help identify a particular product; competitor URLs are not required for automatic discovery. Editing an executed plan creates a fresh investigation and preserves the earlier run.</p>
  </>},
  {id:'videos',title:'Videos & virality',description:'Investigate individual videos within the available evidence.',icon:Monitor,content:<>
   <p className="guide-lead">Ask for a topic, audience or format, and say what you want to learn about the videos. Jev adapts its research questions to that goal.</p>
   <h3>What an individual video record contains</h3><p>Radar collects permitted public metadata for the specific video: its original link, title, description, creator and any available counters or transcript. Indexed provider metadata and publisher metadata retain their own provenance. The original video link is always available.</p>
   <div className="guide-term"><strong>Available text is the evidence boundary</strong><p>Jev analyzes the saved title, description, metadata and any available transcript. Video frames and audio are not analyzed. If a transcript is unavailable, the result says so; an unseen scene, sound or opening hook cannot be inferred from a title.</p></div>
   <h3>Understand the observations</h3><p>Observed views are a recorded counter, not proof of virality. A reported date may come from a search index or publisher declaration; its basis is shown. Sorting by observed views orders the available counters and leaves missing values unknown.</p>
   <h3>Investigate why, without inventing a cause</h3><p>Jev can compare documented title approaches, described formats and audience value, check counterexamples and identify a useful next test. A recurring feature may suggest a hypothesis. Establishing why a video spread needs stronger evidence about audience, distribution, timing and alternatives.</p>
   <Note>A successful research run may establish that the available evidence cannot explain a video’s reach. That limitation is a result to investigate further, not a reason to manufacture an explanation.</Note>
  </>},
  {id:'ecosystem',title:'Jev ecosystem',description:'Useful reference projects to explore.',icon:Sparkles,content:<>
   <p className="guide-lead">Jev supports fast, structured decisions in many kinds of software. These projects illustrate useful patterns around that capability.</p>
   <dl className="guide-definitions">
    <div><dt><a href="https://github.com/superagents-lab/jev-search" target="_blank" rel="noreferrer">Jev Search <ArrowUpRight size={13}/></a></dt><dd>Shows intent, source discovery and ranking as separate decisions, with results arriving as each step finishes.</dd></div>
    <div><dt><a href="https://github.com/browser-use/jev-ultrafast" target="_blank" rel="noreferrer">Browser Use · Jev Ultrafast <ArrowUpRight size={13}/></a></dt><dd>Demonstrates choosing from observed browser targets and checking whether an action actually completed.</dd></div>
    <div><dt><a href="https://github.com/vercel-labs/json-render/blob/3ad381881194e7011ad3ccd6d668033495a06c29/apps/web/lib/jev/README.md" target="_blank" rel="noreferrer">Vercel · json-render Jev experiment <ArrowUpRight size={13}/></a></dt><dd>Explores using structured Jev choices to select interface components and layouts.</dd></div>
   </dl>
   <Note>These are external reference projects, not installed Radar integrations. Radar’s live scene follows its own saved research events. Running another project requires its own setup.</Note>
  </>},
  {id:'costs',title:'Costs & limits',description:'Know what can run and when it stops.',icon:Wallet,content:<>
   <p className="guide-lead">Set your budget in Settings → Spend limits. Defaults are $5 for Jev and $20 for the LLM per investigation.</p>
   <div className="guide-limit-grid"><div><strong>Sources</strong><span>Bounds inspected public pages, individual video records and linked exploration.</span></div><div><strong>Search attempts</strong><span>Bounds provider searches; failed attempts also consume the limit.</span></div><div><strong>Jev requests</strong><span>Bounds inference attempts, tokens and estimated model spend.</span></div><div><strong>Elapsed time</strong><span>Stops research when the configured time allowance is reached.</span></div></div>
   <h3>Understand what the limits change</h3><p>The Jev amount is a starting limit for new investigations; saved plans keep their original allowance. The LLM amount also applies when you resume saved research, counting its existing usage. Changes can be saved when no investigation is running. These ceilings are not charges or spending targets: other limits can stop research sooner.</p>
   <h3>Read cost estimates as estimates</h3><p>Radar reserves a conservative estimated cost before each model request, then updates the estimate from returned token usage. Failed or uncertain requests keep their reservation. Actual provider charges can differ, and search fees are separate. Use your provider’s account controls for billing limits.</p>
   <h3>Check prices for the selected model</h3><p>Under API connections → Research text model → Model prices, limits &amp; data sharing, enter input and output prices per million tokens, or use an available known model price. Prices belong to the exact provider and model. Unknown prices block text requests until configured; choosing another model does not silently reuse the previous model’s rates.</p>
   <h3>Bound text requests separately</h3><p>The same panel includes a maximum number of text requests and output tokens per request. Those limits constrain generated planning, follow-ups and the final answer alongside the LLM dollar allowance. A missing connection or exhausted text allowance leaves the checked source findings available.</p>
   <h3>A partial result is still saved</h3><p>Research can stop when a limit is reached, a provider or website is unavailable, or no remaining prepared action looks useful. The Results summary explains the stop and the unanswered questions. A candidate target is a bounded research aim, not a count of every company in the market.</p>
   <h3>Pause, stop and retry</h3><p>Pause waits for the current bounded action to settle. Cancelling keeps evidence already collected. A provider may still bill a request it already accepted. Review an interruption before deliberately retrying; replaying a saved run does not make new requests.</p>
   <Note>Repeatedly retrying the same exhausted queue does not provide new sources. Review the stop reason and refine the scope or limits when further research is needed.</Note>
  </>},
  {id:'data',title:'Data, replay & exports',description:'Keep the source trail with your research.',icon:ShieldCheck,content:<>
   <p className="guide-lead">Research is saved on the Radar server. Hosted providers receive the information needed for their part of the investigation.</p>
   <dl className="guide-definitions"><div><dt>What stays on the server</dt><dd>Saved investigations, collected evidence, decisions, activity history and optional browser artifacts. API keys are read server-side.</dd></div><div><dt>What goes to providers</dt><dd>Search queries go to the selected search provider. The research question, prepared choices and selected public text go to hosted Jev. When enabled, the selected text model provider also receives the research goal and bounded public evidence excerpts to propose research and draft an answer. These are hosted requests unless you explicitly configure an appropriate self-hosted compatible endpoint.</dd></div><div><dt>What you import</dt><dd>Imported observations retain their declared provenance. Analytics stay local. Public imported URLs are only queued for hosted analysis when you explicitly allow it.</dd></div></dl>
   <h3>Return to saved research</h3><p>Every new visit or refresh opens the Live prompt. Choose Saved to reopen an investigation explicitly. Source dates and evidence remain attached. Reviewing or approving a finding does not silently train Jev or certify its factual accuracy. Rejecting evidence or changing scope hides affected comparisons until they can be reassessed.</p>
   <h3>Replay what actually happened</h3><p>Use Replay machine in the Live view to revisit a saved run, or expand Explore the decisions & replay for individual answers. Replay reconstructs recorded events without searching the web or calling Jev. Return to the latest state before changing the investigation.</p>
   <h3>Take a brief with you</h3><p>Export Markdown, structured JSON, findings CSV, metrics CSV or printable HTML. Reports retain sources and limitations. Default exports omit private import fields, full website snapshots and secret values; review the resulting file before sharing it.</p>
   <h3>Manage retention deliberately</h3><p>Workspace settings includes retention controls; applying deletion removes the affected saved investigations. Deleting a run does not remove copies you already exported through your browser.</p>
  </>},
  {id:'hosting',title:'Self-hosting & access',description:'Run Radar on a regular CPU machine.',icon:Monitor,content:<>
   <p className="guide-lead">Run your own research workspace with your own provider keys. Jev runs at TypeSafe; this application does not need a local GPU.</p>
   <h3>Install and start</h3><p>From the project root, install the application once, add your keys to the server <code>.env</code>, then start it:</p><pre><code>./scripts/install.sh</code></pre><pre aria-label="Startup command"><code>./scripts/run.sh</code></pre><p>Open the address printed by the launcher. The preferred port is <code>8787</code>; if occupied, the launcher may choose another available port.</p>
   <h3>Optional browser rendering</h3><p>Search, public page reading and Jev research work without a browser download. To render JavaScript pages or run the browser tests, install project-local Chromium:</p><pre><code>./scripts/install.sh --with-browser</code></pre><p>Your operating system must also provide Playwright’s platform libraries and sandbox support. The installer does not change system packages or disable the sandbox. Enable rendering in <strong>Settings → Research defaults</strong> when it is ready.</p>
   <h3>Access it from your network</h3><p>The default bind address is <code>0.0.0.0</code>. From another device, open the server’s actual LAN IP and listening port in your browser. <code>0.0.0.0</code> is a listening address, not the browser destination.</p>
   <div className="guide-term"><strong>This installation is a trusted-network workspace</strong><p>There is no user login or per-user isolation. Anyone who can reach the app can read its research and initiate provider requests. Keep it on a trusted network; public internet hosting needs an appropriate access-control setup.</p></div>
   <h3>Keep it on one machine</h3><p>For access only from the server itself, set the following in the project <code>.env</code>, then restart Radar:</p><pre><code>RADAR_HOST=127.0.0.1</code></pre>
   <p>Use the repository README and <code>docs/SETUP.md</code> for requirements and configuration, and <code>docs/DEVELOPMENT.md</code> for contributor checks. Do not run multiple backend processes against the same data directory.</p>
  </>},
  {id:'help',title:'Troubleshooting',description:'Understand a stop and choose the next step.',icon:LifeBuoy,content:<>
   <div className="guide-faq">
    <details open><summary>It stopped quickly. Where are the results?</summary><p>Open Results and the stop explanation. Check Jev’s research approach, the individual objects collected, and the remaining gaps. Jev can refine discovery when useful options and budget remain; blocked sources, exhausted limits or missing primary evidence can still leave the investigation partial.</p></details>
    <details open={query.trim()?true:undefined}><summary>My API key is configured, but nothing starts.</summary><p>Check which connection is missing. TypeSafe enables Jev; Brave enables general web search. Confirm the exact .env names, reload the saved configuration and review the plan’s setup message. A key being present does not guarantee that the provider accepts it.</p></details>
    <details open={query.trim()?true:undefined}><summary>Why does the text model need price estimates?</summary><p>Radar needs the selected model’s input and output prices to enforce its estimated dollar allowance before calling the provider. Configure both under API connections → Research text model. The allowance itself is under Spend limits. Existing usage remains counted when you raise it.</p></details>
    <details open={query.trim()?true:undefined}><summary>What happens if a follow-up proposal fails?</summary><p>If generation is unavailable or malformed, Jev can choose a bounded alternative search when useful options and budget remain. A recorded Jev decision to decline a proposed follow-up is respected. A failed request is not automatically retried or silently sent to another model.</p></details>
    <details open={query.trim()?true:undefined}><summary>Why is a company or a price missing?</summary><p>Only inspected candidates with eligible evidence appear as results. A page may be unavailable, excluded, irrelevant or outside the current limits. Unknown pricing means no usable answer was established in inspected passages.</p></details>
    <details open={query.trim()?true:undefined}><summary>Why are there no popularity numbers?</summary><p>Public search positions are not traffic or audience size. Radar keeps observed visibility separate from popularity and does not combine unrelated platform metrics into an invented score.</p></details>
    <details open={query.trim()?true:undefined}><summary>Can it find every competitor?</summary><p>No finite web investigation can establish an exhaustive list. Narrow the market, review the collected coverage and run a broader follow-up when the decision needs more evidence.</p></details>
    <details open={query.trim()?true:undefined}><summary>What if a website blocks access?</summary><p>Radar records the acquisition problem and keeps the evidence it already has. It respects access restrictions and does not bypass CAPTCHAs. Other permitted sources may still answer the question.</p></details>
    <details open={query.trim()?true:undefined}><summary>Can I continue after closing the browser?</summary><p>The server manages the run and saves its records. Reopen Saved research to inspect its state. If the server itself was interrupted, review the interruption before retrying uncertain provider work.</p></details>
   </div>
   <div className="guide-actions"><button className="secondary" onClick={()=>onSettings('jev')}>Open settings <ArrowRight size={15}/></button></div>
  </>}
 ],[onSettings,onStart,query]);
 const terms=query.toLocaleLowerCase().trim().split(/\s+/).filter(Boolean);
 const matches=sections.filter(section=>{const haystack=[section.title,section.description,textContent(section.content)].join(' ').toLocaleLowerCase();return terms.every(term=>haystack.includes(term))});
 const active=matches.find(section=>section.id===selected)||matches[0];
 function navigate(id:string){setSelected(id);requestAnimationFrame(()=>{article.current?.focus({preventScroll:true});if(window.matchMedia('(max-width: 760px)').matches)article.current?.scrollIntoView({block:'start',behavior:'auto'})})}
 return <div className="radar-guide">
  <header className="guide-header"><div><span className="guide-kicker"><BookOpen size={14}/> RADAR GUIDE</span><h1>Good questions. Clear evidence.</h1><p>A practical guide to setting up Radar, following Jev’s decisions and turning research into your next step.</p></div>{onClose&&<button className="secondary guide-back" onClick={onClose}><ArrowLeft size={15}/> Back to workspace</button>}</header>
  <div className="guide-layout"><aside className="guide-sidebar"><label htmlFor={searchId} className="guide-search-label">Find an answer</label><div className="guide-search"><Search size={16}/><input id={searchId} type="search" value={query} placeholder="Search the guide…" onChange={event=>setQuery(event.target.value)}/>{query&&<button aria-label="Clear guide search" onClick={()=>setQuery('')}><X size={15}/></button>}</div><p className="guide-search-count" role="status">{query?`${matches.length} matching ${matches.length===1?'section':'sections'}`:'Everything you need to get started'}</p><nav aria-label="Guide sections">{matches.map(section=>{const Icon=section.icon;return <button key={section.id} className={active?.id===section.id?'is-active':''} aria-current={active?.id===section.id?'page':undefined} onClick={()=>navigate(section.id)}><Icon size={17}/><span>{section.title}</span><ChevronRight size={14}/></button>})}</nav><div className="guide-sidebar-note"><FileText size={17}/><p>Your research stays connected to its questions, decisions and original sources.</p></div></aside>
   {active?<article className="guide-article" ref={article} tabIndex={-1} aria-label={active.title}><div className="guide-article-heading"><span className="guide-section-icon"><active.icon size={23}/></span><div><h2>{active.title}</h2><p>{active.description}</p></div></div><div className="guide-content">{active.content}</div><footer className="guide-footer"><span>Question → approach → investigation → evidence → comparison</span><button onClick={()=>{setQuery('');navigate('help')}}>Need a hand? <ArrowRight size={13}/></button></footer></article>:<div className="guide-no-results"><Search size={29}/><h2>No matching guide sections</h2><p>Try a shorter term such as “keys”, “pricing”, “replay” or “network”.</p><button className="secondary" onClick={()=>setQuery('')}>Show all sections</button></div>}
  </div>
 </div>;
}
