import {useRef,useEffect,useMemo} from 'react';
import {ReactFlow,Background,Controls,MiniMap,MarkerType,type Node,type Edge,type ReactFlowInstance} from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import {Globe} from 'lucide-react';
import {rows,short,ms,type Mission,type Item} from './api';
export default function ResearchMap({mission,pick,collapsed,filter,selection}:{mission:Mission;pick:(k:string,id:string)=>void;collapsed:boolean;filter:string;selection?:{kind:string;id:string}}){
 const flow=useRef<ReactFlowInstance|null>(null);
 useEffect(()=>{const resize=()=>setTimeout(()=>flow.current?.fitView({padding:.15,maxZoom:.9,duration:0}),150);window.addEventListener('resize',resize);return()=>window.removeEventListener('resize',resize)},[]);
 useEffect(()=>{setTimeout(()=>flow.current?.fitView({padding:.15,maxZoom:.9,duration:0}),100)},[collapsed]);
 const graph=useMemo<{nodes:Node[];edges:Edge[]}>(()=>{const nodes:Node[]=[{id:'goal',position:{x:20,y:100},data:{label:<div className="map-label"><span>RESEARCH GOAL</span><strong>{short(mission.goal,80)}</strong></div>},className:'goal-node',style:{width:225}}];const edges:Edge[]=[];
 const sources=rows(mission,'source').filter(s=>!filter||JSON.stringify(s).toLowerCase().includes(filter.toLowerCase()));
 const domainMap=new Map<string,string>();let i=0;
 for(const s of sources){const domain=new URL(s.url).hostname;if(collapsed&&domainMap.has(domain)){domainMap.set(s.id,domainMap.get(domain)!);continue}const id=s.id;domainMap.set(domain,id);domainMap.set(id,id);nodes.push({id,position:{x:335,y:i*150+15},data:{kind:'source',label:<div className="map-label"><span><Globe size={12}/> {collapsed?'DOMAIN':'SOURCE'} · {s.cache?'CACHE':'FETCHED'}</span><strong>{short(collapsed?domain:s.title,68)}</strong><small>{domain} · {s.coverage.analyzed_chunks} passages</small></div>},className:selection?.id===id?'map-selected':'',style:{width:245}});edges.push({id:'goal-'+id,source:'goal',target:id,label:'found-via',type:'smoothstep'});i++}
 if(collapsed){const grouped=new Map<string,Item[]>();for(const source of sources){const host=new URL(source.url).hostname;grouped.set(host,[...(grouped.get(host)||[]),source])}let index=0;for(const [host,group] of grouped){const ids=new Set(group.map(s=>s.id));const decisions=rows(mission,'decision').filter(d=>ids.has(d.source_id));const findings=rows(mission,'finding').filter(f=>f.source_ids.some((id:string)=>ids.has(id)));const id='summary-'+group[0].id;nodes.push({id,position:{x:690,y:index*150+15},data:{kind:'source',label:<div className="map-label"><span>COLLECTED EVIDENCE</span><strong>{group.length} pages · {decisions.length} typed assessments</strong><small>{findings.length} linked findings · {host}</small></div>},className:'finding-node',style:{width:260}});edges.push({id:'summary-edge-'+id,source:domainMap.get(host)!,target:id,label:'observed-on',type:'smoothstep'});index++}return {nodes,edges};}
 const actionDecisions=rows(mission,'decision').filter(d=>!d.source_id);
 actionDecisions.forEach((d,j)=>{nodes.push({id:d.id,position:{x:20,y:280+j*145},data:{kind:'decision',label:<div className="map-label"><span>JEV · DECISION</span><strong>{d.answers?.next?.choice==='stop'?'Abstained':d.purpose}</strong><small>{ms(d.latency_ms)} · bounded candidate choice</small></div>},className:'decision-node',style:{width:225}});edges.push({id:'goal-'+d.id,source:'goal',target:d.id,label:'asks',type:'smoothstep'});const action=rows(mission,'action').find(a=>a.id===d.answers?.next?.choice);const target=sources.find(s=>s.action_id===action?.id||s.discovered_via===action?.id);if(target)edges.push({id:d.id+'-selected',source:d.id,target:domainMap.get(target.id)||target.id,label:'selected',type:'smoothstep'})});
 const searches=rows(mission,'search');searches.forEach((q,j)=>{nodes.push({id:q.id,position:{x:20,y:280+actionDecisions.length*145+j*135},data:{kind:'search',label:<div className="map-label"><span>{q.provider} · SEARCH</span><strong>{short(q.query,75)}</strong><small>{q.results.length} observed results</small></div>},style:{width:225}});edges.push({id:'goal-'+q.id,source:'goal',target:q.id,label:'query',type:'smoothstep'});for(const source of sources.filter(s=>s.discovered_via===q.id))edges.push({id:q.id+'-'+source.id,source:q.id,target:domainMap.get(source.id)||source.id,label:'found-via',type:'smoothstep'})});
 const decisions=rows(mission,'decision').filter(d=>d.source_id&&sources.some(s=>s.id===d.source_id));
 decisions.forEach((d,j)=>{const sourceId=domainMap.get(d.source_id)||d.source_id;nodes.push({id:d.id,position:{x:690,y:j*128+15},data:{kind:'decision',label:<div className="map-label"><span>TYPED ASSESSMENT</span><strong>{short(d.purpose,58)}</strong><small>{d.cache?'Cached':ms(d.latency_ms)} · {Object.keys(d.answers||{}).length} answers</small></div>},className:'decision-node '+(selection?.id===d.id?'map-selected':''),style:{width:235}});edges.push({id:sourceId+'-'+d.id,source:sourceId,target:d.id,label:'observed-on',type:'smoothstep'})});
 rows(mission,'finding').filter(f=>sources.some(s=>f.source_ids.includes(s.id))).forEach((f,j)=>{nodes.push({id:f.id,position:{x:1030,y:j*115+15},data:{kind:'finding',label:<div className="map-label"><span>{f.status.toUpperCase().replace('_',' ')}</span><strong>{f.subject} · {f.criterion_id}</strong><small>{f.evidence_kind}</small></div>},className:'finding-node '+(selection?.id===f.id?'map-selected':''),style:{width:240}});if(decisions.some(d=>d.id===f.decision_id))edges.push({id:f.decision_id+'-'+f.id,source:f.decision_id,target:f.id,label:f.status==='contradicted'?'contradicts':'supports-claim',type:'smoothstep'})});
 if(!sources.length)rows(mission,'action').slice(0,8).forEach((a,j)=>{nodes.push({id:a.id,position:{x:335,y:j*125},data:{kind:'action',label:<div className="map-label"><span>{a.kind.toUpperCase()} · {a.status}</span><strong>{short(a.value,75)}</strong></div>},style:{width:245}});edges.push({id:'goal-'+a.id,source:'goal',target:a.id,label:'planned',type:'smoothstep'})});
 return {nodes,edges:edges.map(e=>({...e,markerEnd:{type:MarkerType.ArrowClosed,color:'#596069'},style:{stroke:'#485058'},labelStyle:{fill:'#8c939b',fontSize:10},labelBgStyle:{fill:'#14171a'}}))}},[mission.records,collapsed,filter,selection]);
 return <div className="map"><div className="map-legend"><span><i/>Source</span><span><i className="yellow"/>Decision</span><span><i className="green"/>Finding</span></div><ReactFlow nodes={graph.nodes} edges={graph.edges} fitView onInit={instance=>{flow.current=instance;setTimeout(()=>instance.fitView({padding:.15,maxZoom:.9,duration:0}),150)}} minZoom={.12} maxZoom={1.5} nodesDraggable={false} nodesConnectable={false} onNodeClick={(_,n)=>{if(n.data.kind)pick(String(n.data.kind),n.id)}} proOptions={{hideAttribution:true}} colorMode="dark"><Background color="#33383b" gap={24} size={1}/><Controls showInteractive={false}/><MiniMap nodeColor={n=>n.className?.includes('decision')?'#c4ad42':'#465357'} maskColor="#111315bb"/></ReactFlow>{!rows(mission,'action').length&&!rows(mission,'source').length&&<div className="map-empty"><h3>Your investigation starts here</h3><p>Start the reviewed plan to watch real sources and decisions connect.</p></div>}</div>
}
