import {useEffect,useState} from 'react';
import {Activity,BookOpen,CheckCircle2,DollarSign,ExternalLink,KeyRound,RefreshCw,Settings2} from 'lucide-react';
import {api,ms,type Item} from './api';
import TextModelSettings from './TextModelSettings';

export default function SettingsPanel({settings,lenses,busy,work,onSettings,onNotice,onGuide,onExperiments,onRetention}:{settings:Item;lenses:Item[];busy:boolean;work:(fn:()=>Promise<any>)=>Promise<any>;onSettings:(s:Item)=>void;onNotice:(s:string)=>void;onGuide:()=>void;onExperiments:()=>void;onRetention:()=>void}){
 const [tab,setTab]=useState('connections');
 const [profile,setProfile]=useState({...settings.profile});
 const [defaults,setDefaults]=useState<Item>(structuredClone(settings.research_defaults||{}));
 const [jevUsd,setJevUsd]=useState(settings.spend_limits?.jev_usd??5),[textUsd,setTextUsd]=useState(settings.spend_limits?.text_usd??20);
 useEffect(()=>{setDefaults(structuredClone(settings.research_defaults||{}));setJevUsd(settings.spend_limits?.jev_usd??5);setTextUsd(settings.spend_limits?.text_usd??20);},[settings.research_defaults,settings.spend_limits]);
 const save=()=>work(async()=>{await api('/settings',profile,'PUT');if(defaults.limits)await api('/settings/research-defaults',defaults,'PUT');onSettings(await api('/settings'));onNotice('Settings saved. Research defaults apply to new investigations.');});
 const limit=(key:string,value:number)=>setDefaults({...defaults,limits:{...defaults.limits,[key]:value}});
 return <div className="settings-panel"><span className="eyebrow">YOUR WORKSPACE</span><h2>Settings &amp; connections</h2><p>Connect once, then start each investigation with a question.</p>
  <div className="settings-tabs" role="tablist" aria-label="Settings sections">{[['connections','API connections',KeyRound],['spend','Spend limits',DollarSign],['defaults','Research defaults',Settings2],['workspace','Workspace',BookOpen]].map(([id,label,Icon]:any)=><button key={id} role="tab" aria-selected={tab===id} onClick={()=>setTab(id)}><Icon size={15}/>{label}</button>)}</div>
  {tab==='connections'&&<section aria-label="API connections">
   <div className="setup-service"><div><strong>1. Jev by TypeSafe</strong><span>Chooses research actions, assesses sources, and checks evidence.</span></div><span className={'setup-status '+(settings.jev?'configured':'')}>{settings.jev?<><CheckCircle2 size={14}/> Configured</>:'Key needed'}</span></div>
   <div className="setup-service"><div><strong>2. Brave Search</strong><span>Finds websites for prompt-only discovery across the web.</span></div><span className={'setup-status '+(settings.brave?'configured':'')}>{settings.brave?<><CheckCircle2 size={14}/> Configured</>:'Key needed for discovery'}</span></div>
   <div className="key-instructions"><h3>Where to put your keys</h3><ol><li>On the computer running Radar, open the project folder.</li><li>Copy <code>.env.example</code> to <code>.env</code> if the file does not exist.</li><li>Replace the placeholders in <code>.env</code> with your keys:</li></ol><pre>{'TYPESAFE_API_KEY=your_typesafe_key\nBRAVE_SEARCH_API_KEY=your_brave_search_key'}</pre><p>Save the file, then click <strong>Reload keys</strong>. Keys stay on the server and are never returned to this browser. If you are using Radar over your network, edit the file on the server computer.</p><div className="key-links"><a className="text-link" href="https://docs.typesafe.ai/" target="_blank" rel="noreferrer">TypeSafe setup <ExternalLink size={12}/></a><a className="text-link" href="https://api-dashboard.search.brave.com/" target="_blank" rel="noreferrer">Brave Search API <ExternalLink size={12}/></a></div></div>
   <div className="settings-buttons"><button className="primary" disabled={busy} onClick={()=>work(async()=>{const next=await api('/settings/reload',{});onSettings(next);onNotice(next.jev&&next.brave?'Both keys are configured. You can start automatic research.':'Keys reloaded. Check the connection status for any missing key.');})}><RefreshCw size={15}/> Reload keys</button><button className="secondary" disabled={busy||!settings.jev} onClick={()=>work(async()=>{const result=await api('/connection-test',{});onSettings(await api('/settings'));onNotice(result.success?`Jev responded in ${ms(result.latency_ms)} using ${result.model}.`:'Connection test failed: '+result.error);})}><Activity size={15}/> Test Jev connection</button></div><p className="small muted">Reloading makes no inference requests. Testing Jev sends one small paid request. “Configured” means a key is present; it does not verify account access.</p>
   {settings.connection&&<p className="connection-last">{settings.connection.tested_at?<>Last Jev test: <strong>{settings.connection.success?'succeeded':'failed'}</strong> · {new Date(settings.connection.tested_at).toLocaleString()}</>:settings.connection.message||'Run a connection test to verify these credentials.'}</p>}
   <TextModelSettings settings={settings} busy={busy} work={work} onSettings={onSettings} onNotice={onNotice}/>
   <details className="settings-more"><summary>Model, pricing &amp; other research modes</summary><p>Model: <code>{settings.requested_model}</code>. Change <code>JEV_MODEL</code> in the server <code>.env</code> and restart Radar. Other server options are documented in <code>.env.example</code>.</p><p>Jev estimate: ${settings.pricing?.input_usd_per_million}/million input tokens and ${settings.pricing?.output_usd_per_million}/million output tokens. Search provider charges are separate.</p><p className="small muted">{settings.pricing?.source}</p><p>Provided public websites need no search key. Wikipedia search is a limited research mode, not general web discovery. JavaScript rendering is optional.</p></details>
  </section>}
  {tab==='defaults'&&<section aria-label="Research defaults"><p>Starting values for new investigations. Existing research keeps its original plan and limits.</p>{defaults.limits?<><div className="form-grid"><label>Research approach<select value={defaults.lens_id} onChange={e=>setDefaults({...defaults,lens_id:e.target.value})}><option value="auto">Choose from my goal</option>{lenses.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label>Language<select value={defaults.language} onChange={e=>setDefaults({...defaults,language:e.target.value})}>{['en','nl','fr','de','es','it','pt'].map(l=><option key={l}>{l}</option>)}</select></label><label>Region (optional)<input value={defaults.region} onChange={e=>setDefaults({...defaults,region:e.target.value})} placeholder="Leave open, or enter a country"/></label><label>Candidate target<input type="number" min={1} max={8} value={defaults.discovery_target} onChange={e=>setDefaults({...defaults,discovery_target:Number(e.target.value)})}/></label></div><div className="provider-options">{[['brave','Web discovery'],['wikipedia','Wikipedia search']].map(([id,label])=><label className="check" key={id}><input type="checkbox" checked={defaults.providers?.includes(id)} onChange={e=>setDefaults({...defaults,providers:e.target.checked?[...(defaults.providers||[]),id]:defaults.providers.filter((p:string)=>p!==id)})}/>{label}</label>)}<label className="check"><input type="checkbox" checked={!!defaults.browser} onChange={e=>setDefaults({...defaults,browser:e.target.checked})}/> Optional browser rendering</label></div><div className="form-grid">{[['max_pages','Maximum pages',1,80],['max_calls','Maximum Jev attempts',1,200],['max_queries','Maximum search queries',0,20],['wall_seconds','Time limit (seconds)',30,3600],['max_depth','Link depth',0,3]].map(([key,label,min,max])=><label key={String(key)}>{label}<input type="number" min={Number(min)} max={Number(max)} step={key==='usd'?.01:1} value={defaults.limits[String(key)]} onChange={e=>limit(String(key),Number(e.target.value))}/></label>)}</div><p className="small muted">The first limit reached stops the run. Dollar amounts use estimated Jev pricing, not a provider billing cap. Search fees are separate.</p><button className="primary" disabled={busy} onClick={save}>Save research defaults</button></>:<p>Research defaults will be available after the server is updated.</p>}</section>}
  {tab==='spend'&&<section aria-label="Spend limits"><h3>Set a budget for each investigation</h3><p>Jev and your text model have separate allowances. Radar reserves an estimated cost before every request and stops before another request would exceed its allowance.</p><div className="form-grid"><label>Jev allowance (USD)<input aria-label="Jev allowance (USD)" type="number" min={.001} max={1000} step={.01} value={jevUsd} onChange={event=>setJevUsd(Number(event.target.value))}/></label><label>LLM allowance (USD)<input aria-label="LLM allowance (USD)" type="number" min={.001} max={1000} step={.01} value={textUsd} onChange={event=>setTextUsd(Number(event.target.value))}/></label></div><p className="small muted">Defaults: $5 for Jev and $20 for the LLM. These are spending ceilings, not charges or targets. Page, time, request and token limits can stop research sooner. Jev changes apply to new investigations; LLM changes also apply when you resume saved research, preserving its recorded usage.</p><p className="small muted">Amounts are local estimates using configured model prices, not provider billing caps. Unknown or failed requests keep their reserved cost. Search charges are separate. Set account-level limits with your providers for additional control.</p><div className="settings-buttons"><button className="primary" disabled={busy||!Number.isFinite(jevUsd)||!Number.isFinite(textUsd)||jevUsd<.001||textUsd<.001||jevUsd>1000||textUsd>1000} onClick={()=>work(async()=>{onSettings(await api('/settings/spend-limits',{jev_usd:jevUsd,text_usd:textUsd},'PUT'));onNotice('Spend limits saved. Existing usage has been preserved.');})}>Save spend limits</button><button className="text-link" onClick={()=>setTab('connections')}>Configure text model prices</button></div></section>}
  {tab==='workspace'&&<section aria-label="Workspace preferences"><label>Workspace name<input value={profile.name||''} maxLength={80} onChange={e=>setProfile({...profile,name:e.target.value})}/></label><div className="form-grid"><label>Accent color<input type="color" value={profile.accent||'#f1d54a'} onChange={e=>setProfile({...profile,accent:e.target.value})}/></label><label>Retention window (days)<input type="number" min={1} max={365} value={profile.retention_days||30} onChange={e=>setProfile({...profile,retention_days:Number(e.target.value)})}/></label></div><p className="small muted">Retention is applied manually below. Saving this setting does not delete research.</p><button className="primary" disabled={busy} onClick={save}>Save workspace settings</button><div className="what-sent"><BookOpen size={19}/><p>{settings.what_is_sent}</p></div><button className="secondary" onClick={onExperiments}>Edit suggested experiments</button><details className="settings-more danger-zone"><summary>Delete older investigations</summary><p>Apply the saved retention window of {settings.profile?.retention_days||30} days. This permanently deletes matching local investigations and their artifacts.</p><button className="secondary danger" disabled={busy} onClick={onRetention}>Apply retention deletion</button></details></section>}
  <div className="settings-guide"><BookOpen size={16}/><span>New to Radar?</span><button className="text-link" onClick={onGuide}>Open the user guide</button></div>
 </div>;
}
